### ISSUE TITLE
Problems in VSCode with this extension.

### ISSUE THREAD

**Issue by rvanlaar** [fudgepop01/kaitai_ide_vscode#27]
Hi,

I saw this plugin and wanted to try it out. I really like the concept. I'm having a few problems with this extension.

I created a file called `uniquename.ksy` with the contents:

```
meta:
  id: rifx
  endian: le
seq:
  - id: magic
    contents: "RIFX"
  - id: container_len
    type: s4
```
First I got errors with `uniquename` not defined. Those disappeared while trying to reproduce it for this issue.
Now it will only show magic 'Uint8Array' in the KSExplorer. The container_len won't show up.

What's going on?
