### ISSUE TITLE
Error with KS definition: TypeError: Cannot read properties of null (reading 's$1')

### ISSUE THREAD

**Issue by ebw44** [fudgepop01/kaitai_ide_vscode#31]
I'm getting the error `Error with KS definition: TypeError: Cannot read properties of null (reading 's$1')` with any .ksy file when trying to 'compile and examine ksy' or just 'compile to target language' (I tried ts, js, python)
I tried with the example from the readme below as well as the gif example on [http://kaitai.io]
```
seq:
  - id: no_subregions
    type: u4
  - id: has_subregions
    type: example_type
types:
  example_type:
    seq:
      - id: first_child
        type: u4
      - id: second_child
        type: u2
```
kaitai struct vscode version v0.9.0
VScode information:
Version: 1.80.1 (user setup)
Commit: 74f6148eb9ea00507ec113ec51c489d6ffb4b771
Date: 2023-07-12T17:22:07.651Z
Electron: 22.3.14
ElectronBuildId: 21893604
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
